services:
  db:
    image: postgres:16.4
    container_name: cdap-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - backend-network

  loader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdap-loader
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ETL_INPUT_FILE: /app/input/course_project_test.csv
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "src/etl_loader.py"]
    volumes:
      # CSV лежит в корне репозитория (ЛР1), не в Lab2
      - ../course_project_test.csv:/app/input/course_project_test.csv:ro
    restart: "no"
    networks:
      - backend-network

  analytics_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdap-analytics-app
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      loader:
        condition: service_completed_successfully
    ports:
      - "${APP_PORT}:8501"
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: cdap-pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend-network:
    driver: bridge
