apiVersion: v1
kind: Service
metadata:
  name: credit-risk-app
  namespace: cdap-lab3
spec:
  type: NodePort
  selector:
    app: credit-risk-app
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30081
