apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cdap-lab3
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - loader-job.yaml
